name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: print credentials
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jeescobar
          password: dckr_pat_rtub69RHiyU7KzrMhwZGT36CMJU
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jeescobar/laravel:latest